---
- name: Test-04 `ceph_orch_daemon` module
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: stop `osd` service
      ceph_orch_daemon:
        state: stopped
        daemon_id: DAEMON_ID
        daemon_type: osd
