---
- name: Test-06 `ceph_orch_daemon` module
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: start invalid `mon` service
      ceph_orch_daemon:
        state: started
        daemon_id: invalid-DAEMON_ID
        daemon_type: mon
