---
- name: Test-07 `ceph_orch_daemon` module
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: start invalid daemon_type
      ceph_orch_daemon:
        state: started
        daemon_id: DAEMON_ID
        daemon_type: invalid-mon
