---
- name: Test-02 `ceph_config` module 
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Set ceph config `osd_memory_target_autotune` on `osd` with `false`
      ceph_config:
        action: set
        who: osd
        option: osd_memory_target_autotune
        value: false
