---
- name: Test-05 `ceph_config` module 
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Set ceph config `invalid` on `osd` with `true`
      ceph_config:
        action: set
        who: osd
        option: invalid 
        value: true
