---
- name: Test-07 `ceph_config` module 
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Set ceph config `osd_memory_target_autotune` without resource with `true`
      ceph_config:
        action: set
        option: osd_memory_target_autotune
        value: true
