---
- name: Test-08 `ceph_config` module 
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Set ceph without config on `osd` with `true`
      ceph_config:
        action: set
        who: osd
        value: true
