---

- name: Test-01 'ceph_orch_host' module
  hosts: localhost
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Add host node with single label
      ceph_orch_host:
        name: MON_HOSTNAME
        address: MON_IP_ADDRESS
        labels: TestSingleLabel
