---

- name: Test-02 'ceph_orch_host' module
  hosts: localhost
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Add host node with invalid IP address
      ceph_orch_host:
        name: MON_HOSTNAME
        address: invalid-MON_IP_ADDRESS

