---

- name: Test-02 'ceph_orch_host' module
  hosts: localhost
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Delete host node with valid address and name
      ceph_orch_host:
        name: MON_HOSTNAME
        address: MON_IP_ADDRESS
        state: absent
